//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.EntendiLaReferencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="R", Namespace="http://schemas.datacontract.org/2004/07/servicio_web")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApp1.EntendiLaReferencia.Alumno))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApp1.EntendiLaReferencia.Inventario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsFormsApp1.EntendiLaReferencia.Distribuidor))]
    public partial class R : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/servicio_web")]
    [System.SerializableAttribute()]
    public partial class Alumno : WindowsFormsApp1.EntendiLaReferencia.R {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_ControlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Calificacion {
            get {
                return this.CalificacionField;
            }
            set {
                if ((this.CalificacionField.Equals(value) != true)) {
                    this.CalificacionField = value;
                    this.RaisePropertyChanged("Calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Control {
            get {
                return this.Num_ControlField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_ControlField, value) != true)) {
                    this.Num_ControlField = value;
                    this.RaisePropertyChanged("Num_Control");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventario", Namespace="http://schemas.datacontract.org/2004/07/servicio_web")]
    [System.SerializableAttribute()]
    public partial class Inventario : WindowsFormsApp1.EntendiLaReferencia.R {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CantidadField, value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Producto {
            get {
                return this.Nom_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ProductoField, value) != true)) {
                    this.Nom_ProductoField = value;
                    this.RaisePropertyChanged("Nom_Producto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distribuidor", Namespace="http://schemas.datacontract.org/2004/07/servicio_web")]
    [System.SerializableAttribute()]
    public partial class Distribuidor : WindowsFormsApp1.EntendiLaReferencia.R {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entrega {
            get {
                return this.EntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntregaField, value) != true)) {
                    this.EntregaField = value;
                    this.RaisePropertyChanged("Entrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntendiLaReferencia.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistribuidor", ReplyAction="http://tempuri.org/IService1/GetDistribuidorResponse")]
        WindowsFormsApp1.EntendiLaReferencia.Distribuidor GetDistribuidor(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistribuidor", ReplyAction="http://tempuri.org/IService1/GetDistribuidorResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Distribuidor> GetDistribuidorAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlumno", ReplyAction="http://tempuri.org/IService1/GetAlumnoResponse")]
        WindowsFormsApp1.EntendiLaReferencia.Alumno GetAlumno(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlumno", ReplyAction="http://tempuri.org/IService1/GetAlumnoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Alumno> GetAlumnoAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInventario", ReplyAction="http://tempuri.org/IService1/GetInventarioResponse")]
        WindowsFormsApp1.EntendiLaReferencia.Inventario GetInventario(int Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInventario", ReplyAction="http://tempuri.org/IService1/GetInventarioResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Inventario> GetInventarioAsync(int Clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.EntendiLaReferencia.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.EntendiLaReferencia.IService1>, WindowsFormsApp1.EntendiLaReferencia.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.EntendiLaReferencia.Distribuidor GetDistribuidor(int ID) {
            return base.Channel.GetDistribuidor(ID);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Distribuidor> GetDistribuidorAsync(int ID) {
            return base.Channel.GetDistribuidorAsync(ID);
        }
        
        public WindowsFormsApp1.EntendiLaReferencia.Alumno GetAlumno(int ID) {
            return base.Channel.GetAlumno(ID);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Alumno> GetAlumnoAsync(int ID) {
            return base.Channel.GetAlumnoAsync(ID);
        }
        
        public WindowsFormsApp1.EntendiLaReferencia.Inventario GetInventario(int Clave) {
            return base.Channel.GetInventario(Clave);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.EntendiLaReferencia.Inventario> GetInventarioAsync(int Clave) {
            return base.Channel.GetInventarioAsync(Clave);
        }
    }
}
